config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :events
  mount Sidekiq::Web => '/sidekiq'
  root to: 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :web_source

  validates :title, presence: true, length: { in: 2..1000,
    too_long: "Too long!", too_short: "Too short!"
   }
  validates :event_start_date, presence: true
  validates :event_url, presence: true, length: { maximum: 1000 }
  validates :details, :img_url, length: { maximum: 1000 }
  validates :category, :subtitle, length: { maximum: 150 }

  scope :coberlin, -> { where("web_source_id = ?", WebSource.find_by(title: 'Co_Berlin')&.id) }
  scope :berghain, -> { where("web_source_id = ?", WebSource.find_by(title: 'Berghain')&.id) }
  scope :by_title, -> (title) { where("title ILIKE :title", title: "%#{title}%") }
  scope :by_start_date, -> (start_date) { where("event_start_date = ?", start_date) }
  scope :by_end_date, -> (end_date) { where("event_end_date = ?", end_date) }
  scope :by_start_end_date, -> (start_date, end_date) { where("event_start_date >= ? AND event_end_date <= ?", start_date, end_date) }
end

app/models/web_source.rb
class WebSource < ApplicationRecord
  has_many :events, dependent: :destroy

  validates :title, presence: true, length: { minimum: 2, maximum: 100 }
  validates :url, presence: true, length: { maximum: 200 }
  validates :base_url, length: { maximum: 200 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_web_sources, only: [:index]

  def index
    @events = Event.page(params[:page]).per(24)
    @events = @events.by_title(params[:title]) if params[:title].present?
    @events = by_web_source(@events, params[:web_source_id].to_i) if params[:web_source_id].present?
    @events = by_date(@events, params[:event_start_date], params[:event_end_date]) if params[:event_start_date].present? || params[:event_end_date].present?
  end

  private

  def event_params
    params.require(:event).permit(:title, :web_source_id, :event_start_date, :event_end_date)
  end

  def set_web_sources
    @web_sources = WebSource.all
  end

  def by_web_source(events, web_source_id)
    web_source_title = WebSource.find_by(id: web_source_id)&.title
    return if web_source_title.blank?

    case web_source_title
      when 'Co_Berlin'
        return events.coberlin
      when 'Berghain'
        return events.berghain
    end
  end

  def by_date(events, start_date = nil, end_date = nil)
    start_date = start_date.present? ? start_date : nil
    end_date = end_date.present? ? end_date : nil
    return if start_date.blank? && end_date.blank?

    if end_date.blank?
      events = events.by_start_date(start_date)
    elsif start_date.blank?
      events = events.by_end_date(end_date)
    else
      events = events.by_start_end_date(start_date, end_date)
    end
    events
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def show_date(start_date = nil, end_date = nil)
    return [start_date.strftime('%m/%d/%y'), end_date.strftime('%m/%d/%y')].join(' to ') if start_date.present? && end_date.present?
    start_date.strftime('%m/%d/%y')
  end

  def image_url(img_url)
    img_url.blank? ? asset_path('event-default-img.png') : img_url
  end
end

app/views/events/_search.html.erb
<div class='container-fluid bg-light'>
  <%= form_tag events_path, class: 'text-center', method: :get do %>
    <div class='row'>
      <div class='col-sm-3'>
        <div class='form-group'>
          <label for='title'>Title</label>
          <%= text_field_tag :title, params[:title], class: 'form-control', placeholder: 'Title' %>
        </div>
      </div>

      <div class='col-sm-3'>
        <div class='form-group'>
          <label for='web_source'>
            Web Source 
          </label>
          <%= select_tag :web_source_id, options_for_select(@web_sources.collect { |ws| [ws.title, ws.id] }, params[:web_source_id]), include_blank: 'Select a Web Source', class: 'form-control' %>
        </div>
      </div>

      <div class='col-sm-3'>
        <div class='form-group'>
          <label for='event_start_date'>
            Start Date 
          </label>
          <%= date_field_tag :event_start_date, params[:event_start_date], class: 'form-control' %>
        </div>
      </div>

      <div class='col-sm-3'>
        <div class='form-group'>
          <label for='event_end_date'>
            End Date
          </label>
          <%= date_field_tag :event_end_date, params[:event_end_date], class: 'form-control' %>
        </div>
      </div>
    </div>
    <%= submit_tag 'Search', class: 'btn btn-primary' %>
  <% end %>
</div>

<div class='clearfix'></div>

app/views/events/index.html.erb
<%= link_to 'Home', events_path, class: 'btn btn-success' %>

<%= render 'search' %>

<div class='row mt-2'></div>

<% if @events.blank? %>
  <p class='no-results'>Sorry, no results found</p>
<% else %>
  <div id='container'>
    <div class='row'>
      <% @events.each do |event| %>
        <% if event.title.present? && event.event_url.present? %>
          <div class='col-lg-4 col-sm-6 portfolio-item mt-4'>
            <div class='card h-100'>
              <%= link_to event.event_url, target: :_blank do %>
                <%= image_tag image_url(event.img_url), class: 'card-img-top' %>
                <div class='card-body'>
                  <h4 class='card-title'>
                    <strong><%= event.title.titleize %></strong>
                  </h4>
                  <p class='card-text'><%= event&.category&.titleize %></p>
                  <p class='card-text'><%= show_date(event&.event_start_date, event&.event_end_date) %></p>
                  <p class='card-text'><%= event&.subtitle&.titleize %></p>
                  <p class='card-text'><%= truncate(sanitize(event&.details&.titleize), length: 250) %></p>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <%= paginate @events %>
  </div>
<% end %>

<footer class="py-5 bg-dark footer">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; Dalia Research 2018</p>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dalia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>